### ISSUE TITLE
SonarCloud - statikus analízis

### ISSUE THREAD

**Issue by Astrohelo** [BME-MIT-IET/iet-hf-2022-unicode_only#1]
- [x] Admin jog kérése
- [x] SonarCloud beüzemelése
- [x] #8
- [x] Dokumentálás

**Comment by ttomas0520** [comment]
#7

**Comment by ttomas0520** [comment]
A SonarCloud kompatibilitás előállítva, Java és Gradle verzió upgradelve a megfelelő verzióra. #7
